const API='https://gzw-data.dev/api/v1',PAGE_SIZE=48,REPO='Gwazyjustcause/GrayArea',REP_RATE=.006;
const TRADERS=['Handshake','Gunny','Lab Rat','Artisan','Turncoat','Banshee'];
const preferred=['loot_items','weapons','ammo','keys','keycards','medical','backpacks','helmets','vests','plate_carriers','gear','provisions','food','drinks','throwables','night_vision','magazines','suppressors','collimators','scopes','stocks','barrels','handguards','muzzle_devices','tactical_devices','electronics','jewellery','tools','apparel_items'];
let items=[],filtered=[],shown=PAGE_SIZE,category='all',pricedOnly=false,activeItem=null;
const $=s=>document.querySelector(s),clean=s=>String(s??'').replaceAll('_',' ');
const num=v=>{const text=String(v??'').replace(/[$€£\s]/g,'');const normalized=/^\d{1,3}([.,]\d{3})+$/.test(text)?text.replace(/[.,]/g,''):text.replace(/,/g,'');const n=Number(normalized.replace(/[^0-9.-]/g,''));return Number.isFinite(n)?n:0};
const money=v=>num(v)>0?`$${Math.round(num(v)).toLocaleString()}`:'PRICE NEEDED';
const field=(o,names)=>{for(const n of names)if(o[n]!==undefined&&o[n]!==null&&o[n]!=='')return o[n];return null};
const slug=s=>String(s??'').toLowerCase().normalize('NFKD').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
function preferredTrader(name,dataset){const n=name.toLowerCase();if(/perfume|cigarette|cigar|vodka|whiskey|whisky|rum|wine|liquor|alcohol/.test(n))return'Gunny';if(/phone|smartphone/.test(n))return'Lab Rat';if(/credit card/.test(n))return'Artisan';if(dataset==='jewellery'||/ring|necklace|bracelet|watch|gold/.test(n))return'Turncoat';if(/evidence|passport|business id|dslr|camera|laptop|intel/.test(n))return'Banshee';return null}
function normalise(raw,dataset){
  const name=field(raw,['name','title','item_name','Name'])||clean(raw.id)||'Unknown item',value=num(field(raw,['sell_price','sellPrice','grayarea_price']));
  const source=field(raw,['price_source'])||(value?'Wiki / game data':'missing'),status=field(raw,['price_status'])||(value?'verified':'missing');
  const size=String(field(raw,['grid_size','gridSize'])||'').match(/(\d+)\s*[x×]\s*(\d+)/i),width=size?Number(size[1]):num(field(raw,['width','size_x','gridWidth']))||1,height=size?Number(size[2]):num(field(raw,['height','size_y','gridHeight']))||1;
  const image=field(raw,['image','image_url','imageUrl','icon','thumbnail']),type=field(raw,['type','category','class'])||clean(dataset),slots=Math.max(width*height,1),perSlot=value?value/slots:0;
  const decision=!value?'unpriced':perSlot>=1500?'priority':perSlot>=300?'take':perSlot>=100?'decent':'low',hvl=['electronics','funds','jewellery','military_equipment','military_material','vices','valuables'].includes(dataset),accepted=Array.isArray(raw.accepted_by)&&raw.accepted_by.length?raw.accepted_by:TRADERS;
  return{id:`${dataset}:${raw.id||name}`,slug:slug(raw.id||name),name,value,slots,perSlot,image,type,dataset,decision,hvl,source,status,accepted,preferred:field(raw,['preferred_trader'])||preferredTrader(name,dataset),availableFrom:field(raw,['sold_by']),description:field(raw,['description','short_description','details']),raw};
}
async function json(url){const r=await fetch(url);if(!r.ok)throw new Error(`${r.status} ${url}`);return r.json()}
async function load(){try{let cached=[];try{const local=await fetch('data/catalog.json',{cache:'no-store'});if(local.ok)cached=await local.json()}catch{}if(Array.isArray(cached)&&cached.length){items=cached.map(x=>normalise(x.raw||x,x.dataset||'items'));try{const meta=await fetch('data/version.json',{cache:'no-store'});if(meta.ok){const v=await meta.json();$('#dataVersion').textContent=(v.dataVersion||'SYNCED DATA').slice(0,10)}}catch{}renderAfterLoad();return}const version=await json(`${API}/version`),available=version.datasets||version.data?.datasets||preferred,sets=await Promise.allSettled(preferred.filter(x=>available.includes(x)).map(async d=>({d,p:await json(`${API}/${d}?all=true`)})));items=sets.flatMap(x=>x.status==='fulfilled'?(x.value.p.data||[]).map(i=>normalise(i,x.value.d)):[]);$('#dataVersion').textContent=(version.dataVersion||version.data?.dataVersion||'LIVE DATA').slice(0,10);renderAfterLoad()}catch(e){$('#status').innerHTML='Field data is temporarily unavailable. <button onclick="location.reload()">Try again</button>';console.error(e)}}
function renderAfterLoad(){const unique=new Map();for(const i of items)if(!unique.has(i.id))unique.set(i.id,i);items=[...unique.values()];$('#itemCount').textContent=items.length.toLocaleString();$('#pricedCount').textContent=items.filter(i=>i.value).length.toLocaleString();$('#categoryCount').textContent=new Set(items.map(i=>i.dataset)).size;buildCategories();apply()}
function buildCategories(){const counts={};for(const i of items)counts[i.dataset]=(counts[i.dataset]||0)+1;$('#categories').innerHTML=`<button class="category-button active" data-cat="all">All items <small>${items.length}</small></button>`+Object.entries(counts).sort((a,b)=>b[1]-a[1]).map(([c,n])=>`<button class="category-button" data-cat="${c}">${clean(c)} <small>${n}</small></button>`).join('');document.querySelectorAll('.category-button').forEach(b=>b.onclick=()=>{category=b.dataset.cat;shown=PAGE_SIZE;document.querySelectorAll('.category-button').forEach(x=>x.classList.toggle('active',x===b));apply()})}
function apply(){const q=$('#search').value.trim().toLowerCase();filtered=items.filter(i=>(category==='all'||i.dataset===category)&&(!pricedOnly||i.value)&&(!q||`${i.name} ${i.type} ${i.dataset} ${i.description||''}`.toLowerCase().includes(q)));const sort=$('#sort').value;filtered.sort(sort==='value-desc'?(a,b)=>b.value-a.value:sort==='value-slot'?(a,b)=>(b.perSlot-a.perSlot)||Boolean(a.value)-Boolean(b.value):sort==='category'?(a,b)=>a.dataset.localeCompare(b.dataset)||a.name.localeCompare(b.name):(a,b)=>a.name.localeCompare(b.name));$('#resultTitle').textContent=category==='all'?(q?`Search: ${q}`:'All sellable field items'):clean(category);render()}
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function traderBadges(i,compact=false){return `<div class="trader-badges ${compact?'compact':''}" aria-label="Buyers">${TRADERS.map(t=>`<span class="trader-badge ${i.accepted.includes(t)?'accepts':'unknown'} ${i.preferred===t?'preferred':''}" title="${esc(t)}${i.preferred===t?' · reported preferred buyer':''}">${esc(t.split(' ').map(x=>x[0]).join(''))}</span>`).join('')}${i.hvl?`<span class="trader-badge vulture" title="Vulture · high-value loot at reduced payout">V</span>`:''}</div>`}
function card(i){const rep=i.value?i.value*REP_RATE:0;return `<button class="item-card" data-id="${esc(i.id)}"><span class="decision ${i.decision}">${i.decision}</span><div class="item-image">${i.image?`<img loading="lazy" src="${esc(i.image)}" alt="" onerror="this.parentNode.innerHTML='<span class=image-fallback>GA</span>'">`:'<span class="image-fallback">GA</span>'}</div><span class="tag">${esc(clean(i.dataset))}</span><h3>${esc(i.name)}</h3>${traderBadges(i,true)}<div class="price-source ${esc(i.status)}">${i.value?`${esc(i.source)} · ≈${rep.toFixed(rep<10?1:0)} rep`:'PRICE NOT FOUND · ADD IT'}</div><div class="card-meta"><span>${i.slots} slot${i.slots===1?'':'s'}${i.value?` · ${money(i.perSlot)}/slot`:''}</span><span class="price">${money(i.value)}</span></div></button>`}
function render(){$('#status').hidden=filtered.length>0;$('#status').textContent=items.length?(filtered.length?'':'No field items match this search.'):'Loading field data…';$('#grid').innerHTML=filtered.slice(0,shown).map(card).join('');$('#loadMore').hidden=shown>=filtered.length;$('#loadMore').textContent=`LOAD MORE · ${Math.min(filtered.length-shown,PAGE_SIZE)} OF ${filtered.length-shown}`;document.querySelectorAll('.item-card').forEach(c=>c.onclick=()=>openDetail(items.find(i=>i.id===c.dataset.id)))}
function openDetail(i){if(!i)return;activeItem=i;const skip=new Set(['image','image_url','imageUrl','icon','thumbnail','description','name','title','sell_price','buy_price','sold_by','image_source','price_source','price_status']),fields=Object.entries(i.raw).filter(([k,v])=>!skip.has(k)&&['string','number','boolean'].includes(typeof v)&&String(v).length<100).slice(0,16),rep=i.value*REP_RATE;$('#detailContent').innerHTML=`<article class="detail"><div class="detail-top"><div class="detail-image">${i.image?`<img src="${esc(i.image)}" alt="${esc(i.name)}">`:'<span class="image-fallback">GA</span>'}</div><div><span class="tag">${esc(clean(i.dataset))}</span><h2>${esc(i.name)}</h2><p>${esc(i.description||'Sellable field item.')}</p><span class="price-source ${esc(i.status)}">${esc(i.source)}</span></div></div><div class="detail-grid"><div class="detail-stat"><small>Known sale price</small><b>${money(i.value)}</b></div><div class="detail-stat"><small>Value / slot</small><b>${i.value?money(i.perSlot):'—'}</b></div><div class="detail-stat"><small>Estimated reputation</small><b>${i.value?`≈ ${rep.toFixed(rep<10?1:0)} rep`:'—'}</b></div></div><section class="buyer-panel"><small>SELL TO</small>${traderBadges(i)}<p>Green badges are reported buyers.${i.preferred?` <b>${esc(i.preferred)}</b> is the community-reported preferred buyer for this item type.`:''}${i.hvl?' Vulture also accepts high-value loot at a reduced payout.':''}</p></section><div class="seller-advice"><b>Reputation estimate:</b> sale proceeds × 0.006. Community reports indicate rounding or diminishing returns can affect large batches, so verify the final number in-game.${i.availableFrom?`<br><b>Available to buy from:</b> ${esc(i.availableFrom)}.`:''}</div><button class="contribute-button" type="button" data-contribute>ADD OR CORRECT THIS PRICE</button><div class="raw-fields">${fields.map(([k,v])=>`<div class="raw-field"><span>${esc(clean(k))}</span><b>${esc(v)}</b></div>`).join('')}</div></article>`;$('#detailContent [data-contribute]').onclick=()=>openContribution(i);$('#detailDialog').showModal()}
function openContribution(i=activeItem){if(i){$('#contribItem').value=i.name;$('#contribDataset').value=i.dataset;$('#contribId').value=i.raw.id||i.slug}else{$('#contribItem').value='';$('#contribDataset').value='';$('#contribId').value=''}$('#contributionDialog').showModal()}
function submitContribution(e){e.preventDefault();const f=new FormData(e.currentTarget),buyers=f.getAll('buyer').join(', ')||'Unknown / not tested',body=`## Price contribution\n\n- Item: ${f.get('item')}\n- Dataset: ${f.get('dataset')||'Unknown'}\n- Item ID: ${f.get('item_id')||'Unknown'}\n- Sell price: $${f.get('price')}\n- Vendors tested: ${buyers}\n- Best-paying vendor: ${f.get('best_vendor')||'Unknown'}\n- Game version: ${f.get('game_version')||'Current'}\n- Evidence: ${f.get('evidence')||'Not supplied'}\n\nNotes: ${f.get('notes')||'None'}\n\n> Submitted from the Gray Area field guide. Please verify in-game before merging.`,url=`https://github.com/${REPO}/issues/new?title=${encodeURIComponent(`[PRICE] ${f.get('item')} — $${f.get('price')}`)}&body=${encodeURIComponent(body)}&labels=${encodeURIComponent('price-contribution')}`;window.open(url,'_blank','noopener');$('#contributionDialog').close()}
$('#search').addEventListener('input',()=>{shown=PAGE_SIZE;apply()});$('#sort').addEventListener('change',apply);$('#pricedOnly').addEventListener('change',e=>{pricedOnly=e.target.checked;shown=PAGE_SIZE;apply()});$('#loadMore').onclick=()=>{shown+=PAGE_SIZE;render()};$('#clearFilters').onclick=()=>{category='all';pricedOnly=false;$('#pricedOnly').checked=false;$('#search').value='';shown=PAGE_SIZE;document.querySelectorAll('.category-button').forEach((x,n)=>x.classList.toggle('active',n===0));apply()};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());$('#detailDialog').addEventListener('click',e=>{if(e.target===$('#detailDialog'))$('#detailDialog').close()});$('#contributionDialog').addEventListener('click',e=>{if(e.target===$('#contributionDialog'))$('#contributionDialog').close()});$('#openContribution').onclick=()=>openContribution(null);$('#contributionForm').addEventListener('submit',submitContribution);document.addEventListener('keydown',e=>{if(e.key==='/'&&document.activeElement!==$('#search')){e.preventDefault();$('#search').focus()}});load();
